codename = input("Enter Agent's Codename: ")
name = input("Enter agent's real name: ")
gadget = input("Enter assigned gadget: ")
location = input("Enter mission location: ")
number = input("Enter operation number: ")
print(f"*" * 40)
print("     TOP SECRET - AGENT DOSSIER")
print(f"*" * 40)
print()
print(f"Codename: {codename}")
print(f"Real name: {name}")
print(f"Gadget: {gadget}")
print()
print("-" * 40  )
print("MISSION DETAILS:")
print(f"Operation ID:    OP-{number}-{codename}")
print(f"Location:        {location}") 
print("-" * 40  )
print("       *** FOR YOUR EYES ONLY ***")
print("*" * 40)