character_name = input("Enter the character's Name: ")
character_class = input("Enter the character's Class (e.g., Wizard, Rogue, Barbarian): ")
hometown = input("Enter your hometown: ")
quest_item = input("Enter Primary Quest Item: ")
nemesis_name = input("Enter Nemesis's Name: ")

print("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("  KINGDOM OF CODERRA - ADVENTURER'S PASSPORT")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("")
print("Name:      " + character_name)
print("Class:     " + character_class)
print("Origin:    " + hometown)
print("")
print("Known Alias: The " + hometown + " "  + character_class)
print("")
print("----------------------------------------")
print("CURRENT MISSION:")
print("Retrieve the " + quest_item + " from the cluthes of " + nemesis_name + "!")
print("----------------------------------------")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")