name = input("Enter your full name: ")
planet = input("Enter your home planent: ")
species = input("Enter what kind of species you belong to: ")
id_number = input("Enter your ID number (e.g., a sequence of numbers they make up): ")
rank = input("Enter your official rank: ")

print("=" * 40)
print("     GALACTIC FEDERATION ID CARD")
print(f"=" * 40)
print()
print(f"Full Name:       {name}")
print(f"Home Planet:     {planet}")
print(f"Species:         {species}")
print(f"Rank:            {rank}\n")
print("-" * 40)
print(f"ID Code: GF-{id_number}-{planet}")
print("=" * 40)