player = input("Enter player's name: ")
team = input("Enter team name: ")
position = input("Enter player's position: ")
number = input("Enter Jersey number: ")
hometown = input("Enter hometown: ")
print("#" * 40)
print('         LEGENDS OF THE LEAGUE')
print("#" * 40)
print()
print("Player:      " + player)
print("Team:        " + team)
print('Position:    ' + position)
print("Number:      " + number)
print()
print("-" * 40)
print("Player Tag: " + number + "-" + team + "-" + player)
print("Hometown: " + hometown)
print("-" * 40)
print("#" * 40)
