recipe_name = input("Enter recipe name: ")
name = input("Enter chef's name: ")
cuisine = input("Enter cuisine type(e.g., Italian, Mexican): ")
ingredient = input("Enter main ingredient: ")
time = input("Enter prep time (e.g., “45 minutes”): ")
print("+" * 40)
print("         KITCHEN CREATIONS")
print("+" * 40)
print()
print(f'Recipe:     {recipe_name}')
print(f"Cuisine:    {cuisine}")
print(f'Chef:       {name}')
print()
print(f"Signature Dish: {name}'s Famous {cuisine} {recipe_name}\n")
print("-" * 40)
print(f"Main Ingredient: {ingredient}")
print(f"Prep Time:       {time}")
print("-" * 40)